# Generated by Django 3.2.7 on 2021-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
