# Generated by Django 3.2.7 on 2021-09-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210919_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
